# Generated by Django 4.1 on 2023-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=8, unique=True)),
            ],
        ),
    ]
