# Generated by Django 4.1 on 2023-01-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiterservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=8, unique=True)),
                ('opening', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiterservice.table')),
            ],
        ),
    ]
