# Generated by Django 4.1 on 2023-01-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiterservice', '0002_commands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
    ]
