# Generated by Django 4.1 on 2023-01-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiterservice', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('needs_preparation', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiterservice.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('preparation', 'In preparation'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='preparation', max_length=11)),
                ('obs', models.TextField(blank=True)),
                ('preparation_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('commands', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waiterservice.commands')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waiterservice.itemmenu')),
            ],
            options={
                'ordering': ('preparation_time', 'item'),
            },
        ),
    ]
