# Generated by Django 4.1 on 2023-05-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='task',
        ),
    ]
